runtime: go
api_version: go1.9
service: datastore-batchsize-test

env_variables:
  GIN_MODE: release

skip_files:
  - ^app\.yaml$

handlers:
  - url: /.*
    script: _go_app
    secure: always
    redirect_http_response_code: 301
